ZTO_OBJS=\
	zto/node/C25519.o \
	zto/node/Capability.o \
	zto/node/CertificateOfMembership.o \
	zto/node/CertificateOfOwnership.o \
	zto/node/Identity.o \
	zto/node/IncomingPacket.o \
	zto/node/InetAddress.o \
	zto/node/Membership.o \
	zto/node/Multicaster.o \
	zto/node/Network.o \
	zto/node/NetworkConfig.o \
	zto/node/Node.o \
	zto/node/OutboundMulticast.o \
	zto/node/Packet.o \
	zto/node/Path.o \
	zto/node/Peer.o \
	zto/node/Poly1305.o \
	zto/node/Revocation.o \
	zto/node/Salsa20.o \
	zto/node/SelfAwareness.o \
	zto/node/SHA512.o \
	zto/node/Switch.o \
	zto/node/Tag.o \
	zto/node/Topology.o \
	zto/node/Trace.o \
	zto/node/Utils.o \
	zto/controller/EmbeddedNetworkController.o \
	zto/controller/JSONDB.o \
	zto/osdep/ManagedRoute.o \
	zto/osdep/Http.o \
	zto/osdep/OSUtils.o \
	zto/service/SoftwareUpdater.o \
	zto/service/OneService.o \
	zto/ext/http-parser/http_parser.o
