OBJS=\
	zerotierone/ext/lz4/lz4.o \
	zerotierone/ext/json-parser/json.o \
	zerotierone/ext/http-parser/http_parser.o \
	zerotierone/controller/EmbeddedNetworkController.o \
	zerotierone/node/C25519.o \
	zerotierone/node/Capability.o \
	zerotierone/node/CertificateOfMembership.o \
	zerotierone/node/Cluster.o \
	zerotierone/node/Identity.o \
	zerotierone/node/IncomingPacket.o \
	zerotierone/node/InetAddress.o \
	zerotierone/node/Membership.o \
	zerotierone/node/Multicaster.o \
	zerotierone/node/Network.o \
	zerotierone/node/NetworkConfig.o \
	zerotierone/node/Node.o \
	zerotierone/node/OutboundMulticast.o \
	zerotierone/node/Packet.o \
	zerotierone/node/Path.o \
	zerotierone/node/Peer.o \
	zerotierone/node/Poly1305.o \
	zerotierone/node/Revocation.o \
	zerotierone/node/Salsa20.o \
	zerotierone/node/SelfAwareness.o \
	zerotierone/node/SHA512.o \
	zerotierone/node/Switch.o \
	zerotierone/node/Tag.o \
	zerotierone/node/Topology.o \
	zerotierone/node/Utils.o \
	zerotierone/osdep/BackgroundResolver.o \
	zerotierone/osdep/ManagedRoute.o \
	zerotierone/osdep/Http.o \
	zerotierone/osdep/OSUtils.o \
	zerotierone/service/ClusterGeoIpService.o \
	zerotierone/service/ControlPlane.o
